[light]
primary = "#32302f"
secondary = "#3c3836"
tertiary = "#504945"
quaternary = "#665c54"
background0 = "#fbf1c7"
background1 = "#ebdbb2"
background2 = "#d5c4a1"
background3 = "#bdae93"
active = "#d5c4a1"      # background2
inactive = "#3c3836"    # secondary
error = "#c14a4a"       # red
warning = "#bb8125"     # yellow
success = "#538e57"     # green
working = "#46886f"     # cyan
pink = "#a54a62"
red = "#c14a4a"
orange = "#a15725"
yellow = "#bb8125"
green = "#538e57"
cyan = "#46886f"
blue = "#3b708e"
purple = "#983461"

[dark]
primary = "#fbf1c7"
secondary = "#ebdbb2"
tertiary = "#d5c4a1"
quaternary = "#bdae93"
background0 = "#32302f"
background1 = "#3c3836"
background2 = "#504945"
background3 = "#665c54"
active = "#ebdbb2"
inactive = "#3c3836"
error = "#c14a4a"
warning = "#d8a657"
success = "#66ba83"
working = "#076678"
pink = "#d3869b"
red = "#c14a4a"
orange = "#e5915a"
yellow = "#d8a657"
green = "#66ba83"
cyan = "#83a598"
blue = "#4786ab"
purple = "#b16286"
