[light]
primary = "#32302f"
secondary = "#3c3836"
tertiary = "#504945"
quaternary = "#665c54"
accent0 = "#83a598"
background0 = "#fbf1c7"
background1 = "#ebdbb2"
background2 = "#d5c4a1"
background3 = "#bdae93"

[dark]
primary = "#fbf1c7"
secondary = "#ebdbb2"
tertiary = "#d5c4a1"
quaternary = "#bdae93"
accent0 = "#83a598"
background0 = "#32302f"
background1 = "#3c3836"
background2 = "#504945"
background3 = "#665c54"
