[light]
primary = "#32302f"
secondary = "#3c3836"
tertiary = "#504945"
quaternary = "#665c54"
background0 = "#fbf1c7"
background1 = "#ebdbb2"
background2 = "#d5c4a1"
background3 = "#bdae93"
active = "#d5c4a1"
inactive = "#3c3836"
pink = "#d3869b"
red = "#c14a4a"
orange = "#e78a4e"
yellow = "#d8a657"
green = "#78997a"
cyan = "#83a598"
blue = "#076678"
purple = "#b16286"

[dark]
primary = "#fbf1c7"
secondary = "#ebdbb2"
tertiary = "#d5c4a1"
quaternary = "#bdae93"
background0 = "#32302f"
background1 = "#3c3836"
background2 = "#504945"
background3 = "#665c54"
active = "#ebdbb2"
inactive = "#3c3836"
pink = "#d3869b"
red = "#c14a4a"
orange = "#e78a4e"
yellow = "#d8a657"
green = "#78997a"
cyan = "#83a598"
blue = "#076678"
purple = "#b16286"
