# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Config
command_timeout = 3000

# Disable the blank line at the start of the prompt
add_newline = false

format = """
$character\
$os\
$directory\
$git_branch\
$git_status\
[ ](prev_bg)
"""

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:#ebdbb2 bg:prev_fg"
format = "[$symbol]($style)"
disabled = false                # Disabled by default

[os.symbols]
Arch = "󰣇 "
Linux = " "
NixOS = " "
Ubuntu = " "
Windows = " "

[directory]
style = "fg:#ebdbb2 bg:prev_bg"
format = "[ $path]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Contacts" = " "
"Kontakter" = " "
"Desktop" = " "
"Skrivebord" = " "
"Documents" = "󰈙 "
"Dokumenter" = "󰈙 "
"Downloads" = " "
"Nedlastinger" = " "
"Movies" = " "
"Filmer" = " "
"Music" = " "
"Musikk" = " "
"OneDrive" = " "
"Pictures" = " "
"Bilder" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

# VCS Branch
[git_branch]
symbol = " "
style = "fg:#ebdbb2 bg:prev_bg"
format = '[ $symbol$branch]($style)'

[git_state]
rebase = " "
merge = " "
revert = "󰕍 "
cherry_pick = " "
bisect = "󰕝 "
am = "󰛮 "
am_or_rebase = "󰛮 / "
style = "fg:#ebdbb2 bg:prev_bg"
format = ' \([$state($progress_current/$progress_total)]($style)\)'

[git_status]
disabled = false
style = "fg:#ebdbb2 bg:prev_bg"
format = '[ $all_status$ahead_behind]($style)'

[character]
success_symbol = "[](fg:#32302f)"
error_symbol = "[](#c14a4a)"
vimcmd_symbol = "[](#ebdbb2)"
format = "$symbol"

