[style]
border-outer-radius = "0"
border-inner-radius = "0"
border-size = "2"
border-margin = "0"

[fonts]
primary = "The Last Shuriken"
secondary = "Japan Daisuki"
nerd = "JetBrainsMono Nerd Font"

[colors.light]
primary = "#32302f"
secondary = "#3c3836"
tertiary = "#504945"
quaternary = "#665c54"
background0 = "#fbf1c7"
background1 = "#ebdbb2"
background2 = "#d5c4a1"
background3 = "#bdae93"
lighter_pink = "#cb8a9b"
light_pink = "#bb677d"
pink = "#a54a62"
dark_pink = "#823a4d"
darker_pink = "#5f2a38"
lighter_red = "#db9696"
light_red = "#ce7070"
red = "#c14a4a"
dark_red = "#a13737"
darker_red = "#7b2a2a"
lighter_orange = "#d88954"
light_orange = "#ca6d2f"
orange = "#a15725"
dark_orange = "#77401b"
darker_orange = "#4e2a12"
lighter_yellow = "#e1b165"
light_yellow = "#d89c3b"
yellow = "#bb8125"
dark_yellow = "#90641d"
darker_yellow = "#664614"
lighter_green = "#8bbb8f"
light_green = "#6ba96f"
green = "#538e57"
dark_green = "#406e43"
darker_green = "#2d4e30"
lighter_cyan = "#7abaa2"
light_cyan = "#58a98a"
cyan = "#46886f"
dark_cyan = "#356653"
darker_cyan = "#234538"
lighter_blue = "#6da3c2"
light_blue = "#4a8cb2"
blue = "#3b708e"
dark_blue = "#2c536a"
darker_blue = "#1d3746"
lighter_purple = "#cb6794"
light_purple = "#be4179"
purple = "#983461"
dark_purple = "#722749"
darker_purple = "#4c1a31"
# aliases
active = "#d5c4a1"  # background2
inactive = "#3c3836"  # secondary
error = "#c14a4a"  # red
warning = "#bb8125"  # yellow
success = "#538e57"  # green
info = "#46886f"  # cyan
working = "#46886f"  # cyan
important = "#a15725"  # orange

[colors.dark]
primary = "#fbf1c7"
secondary = "#ebdbb2"
tertiary = "#d5c4a1"
quaternary = "#bdae93"
background0 = "#32302f"
background1 = "#3c3836"
background2 = "#504945"
background3 = "#665c54"
lighter_pink = "#eed1d8"
light_pink = "#e1abb9"
pink = "#d3869b"
dark_pink = "#c5607b"
darker_pink = "#b2415f"
lighter_red = "#db9696"
light_red = "#ce7070"
red = "#c14a4a"
dark_red = "#a13737"
darker_red = "#7b2a2a"
lighter_orange = "#f3ccb2"
light_orange = "#ecaf86"
orange = "#e5915a"
dark_orange = "#de742e"
darker_orange = "#bb5d1d"
lighter_yellow = "#ebd2aa"
light_yellow = "#e2bc80"
yellow = "#d8a657"
dark_yellow = "#cc902f"
darker_yellow = "#a37326"
lighter_green = "#acdabc"
light_green = "#89caa0"
green = "#66ba83"
dark_green = "#4aa369"
darker_green = "#3a8053"
lighter_cyan = "#bed0c9"
light_cyan = "#a0bab0"
cyan = "#83a598"
dark_cyan = "#678e7f"
darker_cyan = "#517064"
lighter_blue = "#8ab5ce"
light_blue = "#669fbf"
blue = "#4786ab"
dark_blue = "#386a87"
darker_blue = "#294e63"
lighter_purple = "#d3a6ba"
light_purple = "#c284a0"
purple = "#b16286"
dark_purple = "#964a6c"
darker_purple = "#733954"
# aliases
active = "#ebdbb2"  # secondary
inactive = "#3c3836"  # background1
error = "#c14a4a"  # red
warning = "#d8a657"  # yellow
success = "#66ba83"  # green
info = "#83a598"  # cyan
working = "#83a598"  # cyan
important = "#e5915a"  # orange
