$primary = fbf1c7
$secondary = ebdbb2
$tertiary = d5c4a1
$quaternary = bdae93
$background0 = 32302f
$background1 = 3c3836
$background2 = 504945
$background3 = 665c54
$lighter_pink = eed1d8
$light_pink = e1abb9
$pink = d3869b
$dark_pink = c5607b
$darker_pink = b2415f
$lighter_red = db9696
$light_red = ce7070
$red = c14a4a
$dark_red = a13737
$darker_red = 7b2a2a
$lighter_orange = f3ccb2
$light_orange = ecaf86
$orange = e5915a
$dark_orange = de742e
$darker_orange = bb5d1d
$lighter_yellow = ebd2aa
$light_yellow = e2bc80
$yellow = d8a657
$dark_yellow = cc902f
$darker_yellow = a37326
$lighter_green = acdabc
$light_green = 89caa0
$green = 66ba83
$dark_green = 4aa369
$darker_green = 3a8053
$lighter_cyan = bed0c9
$light_cyan = a0bab0
$cyan = 83a598
$dark_cyan = 678e7f
$darker_cyan = 517064
$lighter_blue = 8ab5ce
$light_blue = 669fbf
$blue = 4786ab
$dark_blue = 386a87
$darker_blue = 294e63
$lighter_purple = d3a6ba
$light_purple = c284a0
$purple = b16286
$dark_purple = 964a6c
$darker_purple = 733954
$active = ebdbb2
$inactive = 3c3836
$error = c14a4a
$warning = d8a657
$success = 66ba83
$info = 83a598
$working = 83a598
$important = e5915a
$border_outer_radius = 0
$border_inner_radius = 0
$border_size = 2
$border_margin = 0
$background_h = ~/.config/themes/japanese-aesthetic/images/japanese-aesthetic_dark-h.png
$background_w = ~/.config/themes/japanese-aesthetic/images/japanese-aesthetic_dark-w.png
$background_v = ~/.config/themes/japanese-aesthetic/images/japanese-aesthetic_dark-v.png
$background_h_greet = ~/.config/themes/japanese-aesthetic/images/japanese-aesthetic_dark-h-greet.png
$cursor_theme = japanese-aesthetic
