gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#c74ded"
      - bold

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#857e89"

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#00e8c6"
      - bold

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#7cb7ff"

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#7cb7ff"

    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - bold

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "#7cb7ff"

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#00e8c6"

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "#7cb7ff"

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#ffe66d"

    # Color for file with unstaged changes
    unstagedChangesColor:
      - "#f39c12"

    # Default text color
    defaultFgColor:
      - "#d5ced9"
