#!/usr/bin/env python3

import subprocess
import os
import urllib.request

CACHE_PATHS = [
    "/tmp/eww/album-art-a.jpg",
    "/tmp/eww/album-art-b.jpg",
]

last_index = -1


def download_and_print(url):
    os.makedirs("/tmp/eww", exist_ok=True)
    global last_index
    last_index = (last_index + 1) % 2
    cache_path = CACHE_PATHS[last_index]

    if url.startswith("http://") or url.startswith("https://"):
        try:
            urllib.request.urlretrieve(url, cache_path)
            print(cache_path, flush=True)
        except Exception:
            print("", flush=True)
    elif url.startswith("file://"):
        path = url[len("file://") :]
        print(path, flush=True)
    else:
        print("", flush=True)


def main():
    process = subprocess.Popen(
        ["playerctl", "--follow", "metadata", "mpris:artUrl"],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        bufsize=1,
    )

    for line in process.stdout:
        url = line.strip()
        download_and_print(url)


if __name__ == "__main__":
    main()
