# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drag
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = force-steam-apps-to-primary-monitor
    match:initial_class = (^steam_app_.*)
    tile = true
    monitor = $primary_monitor
}

windowrule {
    name = force-minecraft-to-primary-monitor
    match:initial_class = (^Minecraft.*)
    tile = true
    monitor = $primary_monitor
}

windowrule {
    name = force-factorio-to-primary-monitor
    match:initial_class = (^factorio)
    tile = true
    monitor = $primary_monitor
}

debug {
    disable_logs = false
    enable_stdout_logs = true
}

