[manager]
cwd = { fg = "#94e2d5" }

hovered         = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#ffe66d", bold = true, italic = true, underline = true }
find_position = { fg = "#ff00aa", bg = "reset", bold = true, italic = true }

marker_copied   = { fg = "#96e072", bg = "#96e072" }
marker_cut      = { fg = "#f92672", bg = "#f92672" }
marker_marked   = { fg = "#00e8c6", bg = "#00e8c6" }
marker_selected = { fg = "#ffe66d", bg = "#ffe66d" }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

count_copied   = { fg = "#1e1e2e", bg = "#96e072" }
count_cut      = { fg = "#1e1e2e", bg = "#f92672" }
count_selected = { fg = "#1e1e2e", bg = "#ffe66d" }

border_symbol = "│"
border_style  = { fg = "#746f77" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#181a16", bg = "#181a16" }

mode_normal = { fg = "#ff00aa", bg = "#373941", bold = true }
mode_select = { fg = "#96e072", bg = "#373941", bold = true }
mode_unset  = { fg = "#ee5d43", bg = "#373941", bold = true }

progress_label  = { fg = "#d5ced9", bold = true }
progress_normal = { fg = "#7cb7ff", bg = "#23262e" }
progress_error  = { fg = "#f92672", bg = "#23262e" }

permissions_t = { fg = "#7cb7ff" }
permissions_r = { fg = "#ffe66d" }
permissions_w = { fg = "#f92672" }
permissions_x = { fg = "#96e072" }
permissions_s = { fg = "#746f77" }

[select]
border   = { fg = "#7cb7ff" }
active   = { fg = "#ff00aa", bold = true }
inactive = {}

[input]
border   = { fg = "#7cb7ff" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border = { fg = "#7cb7ff" }

[tasks]
border  = { fg = "#7cb7ff" }
title   = {}
hovered = { fg = "#ff00aa", underline = true }

[which]
mask            = { bg = "#181a16" }
cand            = { fg = "#00e8c6" }
rest            = { fg = "#23262e" }
desc            = { fg = "#ff00aa" }
separator       = "  "
separator_style = { fg = "#585b70" }

[help]
on      = { fg = "#00e8c6" }
run     = { fg = "#ff00aa" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#45475a", bg = "#cdd6f4" }

[notify]
title_info  = { fg = "#96e072" }
title_warn  = { fg = "#ffe66d" }
title_error = { fg = "#f92672" }

[filetype]

rules = [
	# images
	{ mime = "image/*", fg = "#00e8c6" },

	# media
	{ mime = "{audio,video}/*", fg = "#ffe66d" },

	# archives
	{ mime = "application/*zip", fg = "#ff00aa" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff00aa" },

	# documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#96e072" },

	# by name
	{ name = "*.blend", fg = "#f39c12"},
	{ name = "*.{html,url}", fg = "#c74ded"},

	# fallback
	{ name = "*", fg = "#d5ced9" },
	{ name = "*/", fg = "#7cb7ff" }
]

