yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#c74ded"
      - bold

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#857e89"

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#7cb7ff"

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#7cb7ff"
