return {
	-- "m-demare/attempt.nvim",
	-- dependencies = { "nvim-lua/plenary.nvim" },
	-- config = function()
	-- 	local attempt = require("attempt")
	-- 	attempt.setup({
	-- 		ext_options = { "lua", "py", "cs", "" },
	-- 		run = {
	-- 			cs = { "w", "dotnet script %" },
	-- 			py = { "w !python" }, -- Either table of strings or lua functions
	-- 			js = { "w !node" },
	-- 			lua = { "w", "luafile %" },
	-- 		},
	-- 	})
	-- 	require("telescope").load_extension("attempt")
	--
	-- 	vim.keymap.set("n", "<leader>AN", attempt.new_select, { noremap = true, silent = true }) -- new attempt, selecting extension
	-- 	vim.keymap.set("n", "<leader>AI", attempt.new_input_ext, { noremap = true, silent = true }) -- new attempt, inputing extension
	-- 	vim.keymap.set("n", "<leader>AR", attempt.run, { noremap = true, silent = true }) -- run attempt
	-- 	vim.keymap.set("n", "<leader>AD", attempt.delete_buf, { noremap = true, silent = true }) -- delete attempt from current buffer
	-- 	vim.keymap.set("n", "<leader>AC", attempt.rename_buf, { noremap = true, silent = true }) -- rename attempt from current buffer
	-- 	vim.keymap.set("n", "<leader>AL", "<cmd>Telescope attempt<CR>", { noremap = true, silent = true }) -- search through attempts
	-- end,
}
